### ISSUE TITLE
Document additional setup steps

### ISSUE THREAD

**Issue by jswise** [mggg/maup#22]
This might be too much for the readme file, so maybe the Github wiki (or a new docs folder) would be the place for this.

Getting `maup`'s dependencies to work in my environment required some additional steps that weren't obvious. I'm using conda, Visual Studio Code, and Windows 10. In order to find the DLLs (e.g. MKL), I ended up installing `geopandas` in conda's base environment, as well as the environment I created for `maup`. I'm not sure if both were necessary, but this is what worked for me.

`maup` configures `pytest` to check code coverage, apparently using `pytest-cov`. It's worth mentioning that developers will need to have `pytest-cov` installed.

`pytest-cov` [conflicts with debuggers](https://pytest-cov.readthedocs.io/en/latest/debuggers.html), so you need to disable it in order to run tests in debug mode. You can do this by giving `pytest` the "--no-cov" argument. For example, in Visual Studio Code, this is what my settings.json file looks like:
```
{
    "python.testing.pytestArgs": [
        "tests",
        "--no-cov"
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.nosetestsEnabled": false,
    "python.testing.pytestEnabled": true,
    "python.pythonPath": "C:\\Users\\jswis\\.conda\\envs\\maup\\python.exe"
}
```
You'll need to [edit the settings file](https://github.com/microsoft/vscode-python/issues/693) each time you switch between running code coverage and using debug mode.

**Comment by InnovativeInventor** [comment]
Yep! I just merged in https://github.com/mggg/maup/pull/31 so folks should be able to install with the standard:
```
pip install -r requirements.txt
```
or, with `poetry`:
```
poetry install
```
